version: "3.9"
services:
  doorbell-homeassistant:
    container_name: doorbell-homeassistant
    restart: unless-stopped
    build: .
    pull_policy: build
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /var/doorbell-homeassistant:/doorbell-homeassistant
